{{- range .Values.secrets }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "cluster.namespace" $ }}
  labels:
    {{- include "cluster.labels" $ | nindent 4 }}
{{- with .stringData }}
stringData:
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- with .data }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}
type: {{ .type | default "Opaque" }}
{{- end }}
{{- end }}